function ondemandvidviews = import_ondemandvidviews(filename, startRow, endRow)
%IMPORTFILE2 Import numeric data from a text file as a matrix.
%   ONDEMANDVIDVIEWS = IMPORTFILE2(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   ONDEMANDVIDVIEWS = IMPORTFILE2(FILENAME, STARTROW, ENDROW) Reads data
%   from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   ondemandvidviews = importfile2('on_demand_vid_views.csv', 2, 49);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/09/01 20:44:47

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: datetimes (%{MM/dd/yyyy HH:mm}D)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%{MM/dd/yyyy HH:mm}D%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
ondemandvidviews = table(dataArray{1:end-1}, 'VariableNames', {'Time','Views'});

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% ondemandvidviews.Time=datenum(ondemandvidviews.Time);

