apiVersion: v1
kind: ReplicationController
metadata:
  name: cdnedge
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: cdnedge
        tier: edge
    spec:
      containers:
      - name: cdnadge
        image: gcr.io/api-project-79515284030/cdnedge-image:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            # Path to probe; should be cheap, but representative of typical behavior
            path: /index.html
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
